// templates/ascent-vue/assets/js/components/DarkModeToggle.vue
<script setup>
import Button from '@/volt/Button.vue'
import { useDarkMode } from '@/composables/darkMode'

const { isDark, toggleDarkMode } = useDarkMode()
</script>

<template>
  <Button
    :icon="isDark ? 'pi pi-sun' : 'pi pi-moon'"
    rounded
    text
    severity="secondary"
    :aria-label="isDark ? 'Switch to light mode' : 'Switch to dark mode'"
    :tooltip="isDark ? 'Light mode' : 'Dark mode'"
    :tooltip-options="{ position: 'bottom' }"
    @click="toggleDarkMode"
  />
</template>

// templates/ascent-react/assets/js/components/DarkModeToggle.jsx
import { Button } from 'primereact/button'
import { useDarkMode } from '@/hooks/useDarkMode'

export default function DarkModeToggle() {
  const { isDark, toggleDarkMode } = useDarkMode()

  return (
    <Button
      onClick={toggleDarkMode}
      icon={isDark ? 'pi pi-sun' : 'pi pi-moon'}
      rounded
      text
      severity="secondary"
      aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
      tooltip={isDark ? 'Light mode' : 'Dark mode'}
      tooltipOptions={{ position: 'bottom' }}
    />
  )
}
