// templates/mellow-vue/assets/js/components/InputText.vue
<script setup>
import User from '@/components/ui/icons/User.vue'

import InputBase from '@/components/InputBase.vue'

defineProps({
  label: {
    type: String,
    default: 'Name'
  },
  id: {
    type: String,
    default: 'name'
  },
  placeholder: {
    type: String,
    default: 'Your name'
  },
  error: {
    type: String,
    default: ''
  }
})
</script>

<template>
  <InputBase
    :label="label"
    :id="id"
    type="text"
    :placeholder="placeholder"
    :error="error"
  >
    <template #icon>
      <User class="text-gray h-5 w-5" />
    </template>
    <slot></slot>
  </InputBase>
</template>

// templates/mellow-react/assets/js/components/InputText.jsx
import User from '@/components/ui/icons/User.jsx'
import InputBase from '@/components/InputBase'

export default function InputText(props) {
  return (
    <InputBase
      label="Name"
      id="name"
      type="text"
      placeholder="Your name"
      icon={<User className="text-gray h-5 w-5" />}
      {...props}
    />
  )
}
