// templates/ascent-vue/assets/js/components/ui/separator/Separator.vue
<script setup>
import { computed, ref, useAttrs } from 'vue'
import { twMerge } from 'tailwind-merge'

defineOptions({ inheritAttrs: false })

const props = defineProps({
  orientation: {
    type: String,
    default: 'horizontal',
    validator: (value) => ['horizontal', 'vertical'].includes(value)
  }
})

const attrs = useAttrs()
const element = ref()
const isVertical = computed(() => props.orientation === 'vertical')
const baseClasses = computed(() =>
  isVertical.value ? 'w-px self-stretch' : 'h-px w-full'
)

const forwardedAttrs = computed(() => {
  const {
    class: _class,
    role: _role,
    'aria-orientation': _ariaOrientation,
    'data-orientation': _dataOrientation,
    'data-slot': _dataSlot,
    ...rest
  } = attrs
  return rest
})

defineExpose({ element })
</script>

<template>
  <component
    :is="isVertical ? 'div' : 'hr'"
    ref="element"
    v-bind="forwardedAttrs"
    data-slot="separator"
    :data-orientation="isVertical ? 'vertical' : 'horizontal'"
    :role="isVertical ? 'separator' : undefined"
    :aria-orientation="isVertical ? 'vertical' : undefined"
    :class="
      twMerge(
        'shrink-0 border-0 bg-gray-200 forced-colors:bg-current dark:bg-gray-800',
        baseClasses,
        attrs.class
      )
    "
  />
</template>

// templates/ascent-react/assets/js/components/ui/separator/Separator.jsx
import { forwardRef } from 'react'
import { twMerge } from 'tailwind-merge'

const BASE_CLASSES =
  'shrink-0 border-0 bg-gray-200 forced-colors:bg-current dark:bg-gray-800'

const Separator = forwardRef(function Separator(
  {
    orientation = 'horizontal',
    className,
    role: _role,
    'aria-orientation': _ariaOrientation,
    'data-orientation': _dataOrientation,
    'data-slot': _dataSlot,
    ...props
  },
  ref
) {
  const isVertical = orientation === 'vertical'
  const Component = isVertical ? 'div' : 'hr'

  return (
    <Component
      {...props}
      ref={ref}
      data-slot="separator"
      data-orientation={isVertical ? 'vertical' : 'horizontal'}
      role={isVertical ? 'separator' : undefined}
      aria-orientation={isVertical ? 'vertical' : undefined}
      className={twMerge(
        BASE_CLASSES,
        isVertical ? 'w-px self-stretch' : 'h-px w-full',
        className
      )}
    />
  )
})

export default Separator
