// templates/ascent-vue/assets/js/components/ui/popover/Popover.vue
<script setup>
import {
  autoUpdate,
  computePosition,
  flip,
  offset as floatingOffset,
  shift
} from '@floating-ui/dom'
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  useAttrs,
  useId,
  watch
} from 'vue'
import { twMerge } from 'tailwind-merge'

defineOptions({ inheritAttrs: false })

const props = defineProps({
  /** Matches the native button's `popovertarget`. */
  id: { type: String, default: undefined },
  /** Framework-native controlled state. Omit for native uncontrolled use. */
  open: { type: Boolean, default: undefined },
  /** Initial state when `open` is not controlled. */
  defaultOpen: { type: Boolean, default: false },
  /** Element or element id used only for floating-surface positioning. */
  anchor: { type: [String, Object], default: undefined },
  /** Preferred logical placement. Collision handling may flip it. */
  placement: {
    type: String,
    default: 'bottom-start',
    validator: (value) =>
      [
        'top',
        'top-start',
        'top-end',
        'right',
        'right-start',
        'right-end',
        'bottom',
        'bottom-start',
        'bottom-end',
        'left',
        'left-start',
        'left-end'
      ].includes(value)
  },
  /** Space in pixels between the invoker and floating surface. */
  offset: { type: Number, default: 8 }
})

const emit = defineEmits(['update:open'])
const attrs = useAttrs()
const generatedId = useId()
const content = ref()
const activeInvoker = ref()
const internalOpen = ref(props.defaultOpen)
const nativePopover = ref(false)
const resolvedPlacement = ref(props.placement)
const positionStyle = ref({
  position: 'fixed',
  inset: 'auto',
  left: '0px',
  top: '0px'
})
let cleanupPosition = () => {}

const isControlled = computed(() => props.open !== undefined)
const isOpen = computed(() =>
  isControlled.value ? props.open : internalOpen.value
)
const contentId = computed(
  () =>
    props.id ?? `klean-popover-${generatedId.replace(/[^a-zA-Z0-9_-]/g, '')}`
)
const contentAttrs = computed(() => {
  const {
    class: _class,
    style: _style,
    hidden: _hidden,
    popover: _popover,
    'data-slot': _dataSlot,
    ...rest
  } = attrs
  return rest
})
const contentClasses = computed(() =>
  twMerge(
    [
      'z-50 m-0 w-max max-w-[calc(100vw-1rem)] rounded-md border border-gray-200 bg-white p-4 text-gray-950 shadow-lg outline-none',
      'dark:border-gray-700 dark:bg-gray-950 dark:text-white'
    ],
    attrs.class
  )
)
const dataSlot = computed(() => attrs['data-slot'] ?? 'popover-content')

function invokers() {
  const root = content.value?.getRootNode?.() ?? document

  return [...(root.querySelectorAll?.('[popovertarget]') ?? [])].filter(
    (element) => element.getAttribute('popovertarget') === contentId.value
  )
}

function eventPath(event) {
  return event.composedPath?.() ?? [event.target]
}

function resolveInvoker(candidate) {
  if (candidate?.isConnected) {
    activeInvoker.value = candidate
  }

  if (!activeInvoker.value?.isConnected) {
    activeInvoker.value = invokers()[0]
  }

  return activeInvoker.value
}

function resolveAnchor() {
  if (typeof props.anchor === 'string') {
    const root = content.value?.getRootNode?.() ?? document
    const element =
      root.getElementById?.(props.anchor) ??
      document.getElementById(props.anchor)

    if (element?.isConnected) return element
  } else if (props.anchor?.isConnected) {
    return props.anchor
  }

  return resolveInvoker()
}

function syncInvokerAria() {
  for (const invoker of invokers()) {
    invoker.setAttribute('aria-controls', contentId.value)
    invoker.setAttribute('aria-expanded', String(isOpen.value))
  }
}

function popoverIsShowing() {
  if (!content.value || !nativePopover.value) return false

  try {
    return content.value.matches(':popover-open')
  } catch {
    return false
  }
}

function syncNativePopover() {
  if (!content.value || !nativePopover.value) return

  const showing = popoverIsShowing()

  try {
    if (isOpen.value && !showing) {
      content.value.showPopover({ source: resolveInvoker() })
    } else if (!isOpen.value && showing) {
      content.value.hidePopover()
    }
  } catch {
    // A rapid native toggle can briefly make the requested state redundant.
  }
}

function setOpen(nextOpen, { restoreFocus = false } = {}) {
  if (!isControlled.value) internalOpen.value = nextOpen
  emit('update:open', nextOpen)

  nextTick(() => {
    syncInvokerAria()
    syncNativePopover()

    const invoker = resolveInvoker()
    if (!nextOpen && restoreFocus && invoker?.isConnected) {
      invoker.focus({ preventScroll: true })
    }
  })
}

function close({ restoreFocus = isOpen.value } = {}) {
  setOpen(false, { restoreFocus })
}

function open(source) {
  resolveInvoker(source)
  setOpen(true)
}

function handleNativeToggle(event) {
  const nextOpen = event.newState === 'open'
  const shouldRestoreFocus =
    !nextOpen && event.source?.getAttribute?.('popovertargetaction') === 'hide'
  if (nextOpen) resolveInvoker(event.source)
  if (nextOpen === isOpen.value) return

  if (!isControlled.value) internalOpen.value = nextOpen
  emit('update:open', nextOpen)
  syncInvokerAria()

  if (isControlled.value) nextTick(syncNativePopover)

  if (shouldRestoreFocus) {
    nextTick(() => {
      const invoker = resolveInvoker()
      if (invoker?.isConnected) invoker.focus({ preventScroll: true })
    })
  }
}

function matchingInvokerFromEvent(event) {
  const candidate = eventPath(event).find(
    (element) => element?.getAttribute?.('popovertarget') === contentId.value
  )
  return candidate?.getAttribute('popovertarget') === contentId.value
    ? candidate
    : undefined
}

function handleFallbackInvokerClick(event) {
  const invoker = matchingInvokerFromEvent(event)
  if (!invoker) return

  resolveInvoker(invoker)
  const action = invoker.getAttribute('popovertargetaction') ?? 'toggle'

  if (action === 'show') setOpen(true)
  else if (action === 'hide') setOpen(false, { restoreFocus: true })
  else setOpen(!isOpen.value)
}

function handleOutsidePointer(event) {
  const path = eventPath(event)
  const invoker = resolveInvoker()
  const anchor = resolveAnchor()

  if (
    path.includes(content.value) ||
    (invoker && (path.includes(invoker) || invoker.contains?.(event.target))) ||
    (anchor && (path.includes(anchor) || anchor.contains?.(event.target))) ||
    invokers().some(
      (invoker) => path.includes(invoker) || invoker.contains(event.target)
    )
  ) {
    return
  }

  setOpen(false)
}

function handleEscape(event) {
  if (event.key !== 'Escape') return

  if (nativePopover.value) {
    const openPopovers = [...document.querySelectorAll(':popover-open')]
    if (openPopovers.at(-1) !== content.value) return
  }

  event.preventDefault()
  setOpen(false, { restoreFocus: true })
}

async function updatePosition() {
  const anchor = resolveAnchor()
  if (!isOpen.value || !anchor || !content.value) return

  const { x, y, placement } = await computePosition(anchor, content.value, {
    placement: props.placement,
    strategy: 'fixed',
    middleware: [floatingOffset(props.offset), flip(), shift({ padding: 8 })]
  })

  resolvedPlacement.value = placement
  positionStyle.value = {
    position: 'fixed',
    inset: 'auto',
    left: `${x}px`,
    top: `${y}px`
  }
}

function stopOpenEffects() {
  cleanupPosition()
  cleanupPosition = () => {}
  document.removeEventListener('pointerdown', handleOutsidePointer, true)
  document.removeEventListener('keydown', handleEscape)
}

async function syncOpenEffects() {
  stopOpenEffects()
  await nextTick()
  syncInvokerAria()
  syncNativePopover()

  const anchor = resolveAnchor()
  if (!isOpen.value || !anchor || !content.value) return

  cleanupPosition = autoUpdate(anchor, content.value, updatePosition)

  document.addEventListener('keydown', handleEscape)
  document.addEventListener('pointerdown', handleOutsidePointer, true)
}

watch(
  () => [
    isOpen.value,
    props.anchor,
    props.placement,
    props.offset,
    activeInvoker.value
  ],
  syncOpenEffects,
  { flush: 'post' }
)

onMounted(() => {
  nativePopover.value =
    typeof content.value?.showPopover === 'function' &&
    typeof content.value?.hidePopover === 'function'
  resolveInvoker()
  syncInvokerAria()

  if (!nativePopover.value) {
    document.addEventListener('click', handleFallbackInvokerClick)
  }

  syncOpenEffects()
})

onBeforeUnmount(() => {
  stopOpenEffects()
  document.removeEventListener('click', handleFallbackInvokerClick)
})

defineExpose({ content, close, open })
</script>

<template>
  <div
    ref="content"
    v-bind="contentAttrs"
    :id="contentId"
    popover="auto"
    :hidden="!nativePopover && !isOpen"
    :data-slot="dataSlot"
    :data-state="isOpen ? 'open' : 'closed'"
    :data-placement="resolvedPlacement"
    :class="contentClasses"
    :style="[positionStyle, attrs.style]"
    @toggle="handleNativeToggle"
  >
    <slot :open="isOpen" :close="close" />
  </div>
</template>

// templates/ascent-react/assets/js/components/ui/popover/Popover.jsx
import {
  autoUpdate,
  computePosition,
  flip,
  offset as floatingOffset,
  shift
} from '@floating-ui/dom'
import {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState
} from 'react'
import { twMerge } from 'tailwind-merge'

const BASE_CLASSES = [
  'z-50 m-0 w-max max-w-[calc(100vw-1rem)] rounded-md border border-gray-200 bg-white p-4 text-gray-950 shadow-lg outline-none',
  'dark:border-gray-700 dark:bg-gray-950 dark:text-white'
]

const Popover = forwardRef(function Popover(
  {
    id,
    open: controlledOpen,
    defaultOpen = false,
    anchor,
    onOpenChange,
    placement = 'bottom-start',
    offset = 8,
    className,
    style,
    'data-slot': dataSlot = 'popover-content',
    children,
    ...contentProps
  },
  forwardedRef
) {
  const generatedId = useId().replace(/[^a-zA-Z0-9_-]/g, '')
  const contentId = id ?? `klean-popover-${generatedId}`
  const contentRef = useRef(null)
  const activeInvoker = useRef(null)
  const [referenceVersion, setReferenceVersion] = useState(0)
  const [internalOpen, setInternalOpen] = useState(defaultOpen)
  const [supportsNative, setSupportsNative] = useState(false)
  const [resolvedPlacement, setResolvedPlacement] = useState(placement)
  const [positionStyle, setPositionStyle] = useState({
    position: 'fixed',
    inset: 'auto',
    left: 0,
    top: 0
  })
  const isControlled = controlledOpen !== undefined
  const isOpen = isControlled ? controlledOpen : internalOpen
  const latestOpen = useRef(isOpen)
  latestOpen.current = isOpen

  const invokers = useCallback(() => {
    const root = contentRef.current?.getRootNode?.() ?? document

    return [...(root.querySelectorAll?.('[popovertarget]') ?? [])].filter(
      (element) => element.getAttribute('popovertarget') === contentId
    )
  }, [contentId])

  const eventPath = (event) =>
    event.nativeEvent?.composedPath?.() ??
    event.composedPath?.() ?? [event.target]

  const resolveInvoker = useCallback(
    (candidate) => {
      if (candidate?.isConnected && activeInvoker.current !== candidate) {
        activeInvoker.current = candidate
        setReferenceVersion((version) => version + 1)
      }

      if (!activeInvoker.current?.isConnected) {
        const fallback = invokers()[0]
        if (activeInvoker.current !== fallback) {
          activeInvoker.current = fallback
          setReferenceVersion((version) => version + 1)
        }
      }

      return activeInvoker.current
    },
    [contentId, invokers]
  )

  const resolveAnchor = useCallback(() => {
    if (typeof anchor === 'string') {
      const root = contentRef.current?.getRootNode?.() ?? document
      const element =
        root.getElementById?.(anchor) ?? document.getElementById(anchor)

      if (element?.isConnected) return element
    } else if (anchor?.isConnected) {
      return anchor
    }

    return resolveInvoker()
  }, [anchor, resolveInvoker])

  const syncInvokerAria = useCallback(() => {
    for (const invoker of invokers()) {
      invoker.setAttribute('aria-controls', contentId)
      invoker.setAttribute('aria-expanded', String(latestOpen.current))
    }
  }, [contentId, invokers])

  const popoverIsShowing = useCallback(() => {
    if (!supportsNative || !contentRef.current) return false

    try {
      return contentRef.current.matches(':popover-open')
    } catch {
      return false
    }
  }, [supportsNative])

  const syncNativePopover = useCallback(() => {
    if (!supportsNative || !contentRef.current) return

    const showing = popoverIsShowing()

    try {
      if (latestOpen.current && !showing) {
        contentRef.current.showPopover({ source: resolveInvoker() })
      } else if (!latestOpen.current && showing) {
        contentRef.current.hidePopover()
      }
    } catch {
      // A rapid native toggle can briefly make the requested state redundant.
    }
  }, [popoverIsShowing, resolveInvoker, supportsNative])

  const requestOpen = useCallback(
    (nextOpen, { restoreFocus = false } = {}) => {
      if (!isControlled) setInternalOpen(nextOpen)
      onOpenChange?.(nextOpen)

      queueMicrotask(() => {
        syncInvokerAria()
        syncNativePopover()

        const invoker = resolveInvoker()
        if (!nextOpen && restoreFocus && invoker?.isConnected) {
          invoker.focus({ preventScroll: true })
        }
      })
    },
    [
      isControlled,
      onOpenChange,
      resolveInvoker,
      syncInvokerAria,
      syncNativePopover
    ]
  )

  useImperativeHandle(
    forwardedRef,
    () => ({
      content: contentRef.current,
      open: (source) => {
        resolveInvoker(source)
        requestOpen(true)
      },
      close: ({ restoreFocus = latestOpen.current } = {}) =>
        requestOpen(false, { restoreFocus })
    }),
    [requestOpen, resolveInvoker]
  )

  useEffect(() => {
    const native =
      typeof contentRef.current?.showPopover === 'function' &&
      typeof contentRef.current?.hidePopover === 'function'
    setSupportsNative(native)
    resolveInvoker()
    syncInvokerAria()

    if (native) return

    function handleFallbackInvokerClick(event) {
      const candidate = eventPath(event).find(
        (element) => element?.getAttribute?.('popovertarget') === contentId
      )
      if (candidate?.getAttribute('popovertarget') !== contentId) return

      resolveInvoker(candidate)
      const action = candidate.getAttribute('popovertargetaction') ?? 'toggle'

      if (action === 'show') requestOpen(true)
      else if (action === 'hide') {
        requestOpen(false, { restoreFocus: true })
      } else requestOpen(!latestOpen.current)
    }

    document.addEventListener('click', handleFallbackInvokerClick)
    return () =>
      document.removeEventListener('click', handleFallbackInvokerClick)
  }, [contentId, requestOpen, resolveInvoker, syncInvokerAria])

  useEffect(() => {
    syncInvokerAria()
    syncNativePopover()

    const anchorElement = resolveAnchor()
    if (!isOpen || !anchorElement || !contentRef.current) return

    const updatePosition = async () => {
      const result = await computePosition(anchorElement, contentRef.current, {
        placement,
        strategy: 'fixed',
        middleware: [floatingOffset(offset), flip(), shift({ padding: 8 })]
      })

      setResolvedPlacement(result.placement)
      setPositionStyle({
        position: 'fixed',
        inset: 'auto',
        left: result.x,
        top: result.y
      })
    }

    return autoUpdate(anchorElement, contentRef.current, updatePosition)
  }, [
    isOpen,
    offset,
    placement,
    referenceVersion,
    resolveAnchor,
    resolveInvoker,
    syncInvokerAria,
    syncNativePopover
  ])

  useEffect(() => {
    if (!isOpen) return

    function handleOutsidePointer(event) {
      const path = eventPath(event)
      const invoker = resolveInvoker()
      const anchorElement = resolveAnchor()

      if (
        path.includes(contentRef.current) ||
        (invoker &&
          (path.includes(invoker) || invoker.contains?.(event.target))) ||
        (anchorElement &&
          (path.includes(anchorElement) ||
            anchorElement.contains?.(event.target))) ||
        invokers().some(
          (invoker) => path.includes(invoker) || invoker.contains(event.target)
        )
      ) {
        return
      }

      requestOpen(false)
    }

    function handleEscape(event) {
      if (event.key !== 'Escape') return

      if (supportsNative) {
        const openPopovers = [...document.querySelectorAll(':popover-open')]
        if (openPopovers.at(-1) !== contentRef.current) return
      }

      event.preventDefault()
      requestOpen(false, { restoreFocus: true })
    }

    document.addEventListener('keydown', handleEscape)
    document.addEventListener('pointerdown', handleOutsidePointer, true)

    return () => {
      document.removeEventListener('pointerdown', handleOutsidePointer, true)
      document.removeEventListener('keydown', handleEscape)
    }
  }, [
    isOpen,
    invokers,
    requestOpen,
    resolveAnchor,
    resolveInvoker,
    supportsNative
  ])

  function handleNativeToggle(event) {
    const nativeEvent = event.nativeEvent
    const nextOpen = nativeEvent.newState === 'open'
    const shouldRestoreFocus =
      !nextOpen &&
      nativeEvent.source?.getAttribute?.('popovertargetaction') === 'hide'
    if (nextOpen) resolveInvoker(nativeEvent.source)
    if (nextOpen === latestOpen.current) return

    if (!isControlled) setInternalOpen(nextOpen)
    onOpenChange?.(nextOpen)
    queueMicrotask(syncInvokerAria)

    if (isControlled) queueMicrotask(syncNativePopover)

    if (shouldRestoreFocus) {
      queueMicrotask(() => {
        const invoker = resolveInvoker()
        if (invoker?.isConnected) invoker.focus({ preventScroll: true })
      })
    }
  }

  const close = ({ restoreFocus = latestOpen.current } = {}) =>
    requestOpen(false, { restoreFocus })

  return (
    <div
      {...contentProps}
      ref={contentRef}
      id={contentId}
      popover="auto"
      hidden={!supportsNative && !isOpen}
      data-slot={dataSlot}
      data-state={isOpen ? 'open' : 'closed'}
      data-placement={resolvedPlacement}
      className={twMerge(BASE_CLASSES, className)}
      style={{ ...positionStyle, ...style }}
      onToggle={handleNativeToggle}
    >
      {typeof children === 'function'
        ? children({ open: isOpen, close })
        : children}
    </div>
  )
})

export default Popover
