// create-sails/template/config/react/assets/js/pages/example.js
import { Link } from "@inertiajs/react";
export default function Hello({ quote }) {
  return (
    <div className="flex h-screen flex-col items-center justify-center space-y-8 text-center text-gray-700">
      <p className="text-xl">{quote}</p>
      <Link href="/" className="text-purple-600 underline">
        Back to Home
      </Link>
    </div>
  );
}

// create-sails/template/config/vue/assets/js/pages/example.vue
<script setup>
import { Link } from '@inertiajs/vue3'

const { quote } = defineProps({
  quote: String
})
</script>

<template>
  <div
    class="flex h-screen flex-col items-center justify-center space-y-8 text-center text-gray-700"
  >
    <p class="text-xl">{{ quote }}</p>
    <Link href="/" class="text-purple-600 underline"> Back to Home </Link>
  </div>
</template>
