// templates/ascent-react/assets/js/pages/settings/profile.jsx
import { useState } from 'react'
import { Head, usePage, useForm, router } from '@inertiajs/react'

import DashboardLayout from '@/layouts/DashboardLayout'
import SettingsLayout from '@/layouts/SettingsLayout.jsx'

import { InputText } from 'primereact/inputtext'
import { Button } from 'primereact/button'
import { Avatar } from 'primereact/avatar'
import { Message } from 'primereact/message'
import { ConfirmDialog } from 'primereact/confirmdialog'
import { confirmDialog } from 'primereact/confirmdialog'
import ImageUpload from '@/components/ImageUpload'

ProfileSettings.layout = (page) => (
  <DashboardLayout title="Profile" maxWidth="narrow">
    {page}
  </DashboardLayout>
)

export default function ProfileSettings() {
  const loggedInUser = usePage().props.loggedInUser

  const { data, setData, ...form } = useForm({
    email: loggedInUser.email,
    fullName: loggedInUser.fullName,
    avatar: null
  })

  const {
    data: deleteAccountData,
    setData: setDeleteAccountData,
    ...deleteAccountForm
  } = useForm({
    password: undefined
  })

  function updateProfile(e) {
    e.preventDefault()
    form.patch(`/settings/profile`, {
      preserveScroll: true,
      preserveState: true,
      onError: (errors) => {
        console.error('Update failed:', errors)
      }
    })
  }

  function confirmDeleteAccount() {
    confirmDialog({
      message:
        'Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.',
      header: 'Delete Account',
      icon: 'pi pi-exclamation-triangle',
      acceptClassName: 'p-button-danger',
      accept: () => {
        deleteAccountForm.delete('/settings/profile')
      }
    })
  }

  function signOutEverywhere() {
    router.delete('/logout')
  }

  return (
    <>
      <Head title="Profile Settings | Ascent React"></Head>
      <ConfirmDialog style={{ width: '32rem' }} />

      <div className="max-w-2xl space-y-12">
        {/* Profile Header */}
        <header className="flex items-center space-x-4">
          <Avatar
            image={loggedInUser.currentAvatarUrl}
            label={loggedInUser.initials}
            size="large"
            shape="circle"
          />
          <div>
            <h2 className="text-lg font-medium text-gray-900">
              {loggedInUser.fullName}
            </h2>
            <p className="text-sm text-gray-500">{loggedInUser.email}</p>
          </div>
        </header>

        {/* Profile Information */}
        <section className="space-y-6">
          <div>
            <h3 className="mb-4 text-sm font-medium text-gray-900">
              Profile Information
            </h3>
            <p className="mb-6 text-sm text-gray-500">
              Update your personal details and contact information.
            </p>
          </div>

          <form onSubmit={updateProfile} className="space-y-4">
            {/* Avatar Upload */}
            <div>
              <label className="mb-2 block text-sm font-medium text-gray-700">
                Avatar
              </label>
              <ImageUpload
                currentImageUrl={loggedInUser.avatarUrl}
                onImageSelect={(file) => setData('avatar', file)}
              />
              {form.errors.avatar && (
                <Message
                  severity="error"
                  text={form.errors.avatar}
                  className="mt-2"
                />
              )}
            </div>

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <label
                  htmlFor="fullName"
                  className="mb-1 block text-sm text-gray-700"
                >
                  Full Name
                </label>
                <InputText
                  id="fullName"
                  value={data.fullName}
                  onChange={(e) => setData('fullName', e.target.value)}
                  className="w-full"
                />
              </div>

              <div>
                <label
                  htmlFor="email"
                  className="mb-1 block text-sm text-gray-700"
                >
                  Email Address
                </label>
                <InputText
                  id="email"
                  type="email"
                  value={data.email}
                  onChange={(e) => setData('email', e.target.value)}
                  className="w-full"
                />
              </div>
            </div>
            <div className="flex items-center justify-end space-x-3">
              {form.recentlySuccessful && (
                <span className="text-sm text-green-600">Saved</span>
              )}
              <Button
                type="submit"
                label={form.processing ? 'Saving changes...' : 'Save changes'}
                loading={form.processing}
                size="small"
                outlined
              />
            </div>
          </form>
        </section>

        {/* Account Actions */}
        <section className="space-y-6">
          <div>
            <h3 className="mb-4 text-sm font-medium text-gray-900">
              Account Actions
            </h3>
            <p className="mb-6 text-sm text-gray-500">
              Manage your account security and data.
            </p>
          </div>

          <div className="space-y-4">
            {/* Sign out everywhere card */}
            <div className="rounded-lg border border-orange-200 bg-orange-50 p-4 shadow-sm sm:p-6">
              <div className="flex flex-col space-y-4 sm:flex-row sm:items-start sm:justify-between sm:space-y-0">
                <div className="flex items-start space-x-3">
                  <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-lg bg-orange-50">
                    <i className="pi pi-sign-out text-orange-600"></i>
                  </div>
                  <div className="min-w-0 flex-1">
                    <h4 className="text-sm font-medium text-orange-900">
                      Sign out everywhere
                    </h4>
                    <p className="mt-1 text-sm text-orange-700">
                      Sign out from all devices and browser sessions for
                      enhanced security.
                    </p>
                  </div>
                </div>
                <div className="flex justify-end sm:ml-4 sm:flex-shrink-0">
                  <Button
                    label="Sign out"
                    onClick={signOutEverywhere}
                    size="small"
                    className="w-full px-4 py-2 text-sm sm:w-auto"
                    outlined
                    severity="warning"
                    icon="pi pi-sign-out"
                  />
                </div>
              </div>
            </div>

            {/* Delete account card */}
            <div className="rounded-lg border border-red-200 bg-red-50 p-4 shadow-sm sm:p-6">
              <div className="flex flex-col space-y-4 sm:flex-row sm:items-start sm:justify-between sm:space-y-0">
                <div className="flex items-start space-x-3">
                  <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-lg bg-red-100">
                    <i className="pi pi-trash text-red-600"></i>
                  </div>
                  <div className="min-w-0 flex-1">
                    <h4 className="text-sm font-medium text-red-900">
                      Delete account
                    </h4>
                    <p className="mt-1 text-sm text-red-700">
                      Permanently delete your account and all associated data.
                      This action cannot be undone.
                    </p>
                  </div>
                </div>
                <div className="flex justify-end sm:ml-4 sm:flex-shrink-0">
                  <Button
                    label="Delete"
                    onClick={confirmDeleteAccount}
                    severity="danger"
                    size="small"
                    className="w-full px-4 py-2 text-sm sm:w-auto"
                    icon="pi pi-trash"
                    outlined
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  )
}

// templates/ascent-vue/assets/js/pages/settings/profile.vue
<script setup>
import { computed } from 'vue'
import { Head, usePage, useForm, router } from '@inertiajs/vue3'
import { useConfirm } from '@/volt/useconfirm'
import InputText from '@/volt/inputtext'
import Button from '@/volt/button'
import Avatar from '@/volt/avatar'
import Message from '@/volt/message'
import ConfirmDialog from '@/volt/confirmdialog'
import ImageUpload from '@/components/ImageUpload.vue'

const page = usePage()
const confirm = useConfirm()

const loggedInUser = computed(() => page.props.loggedInUser)

const form = useForm({
  email: loggedInUser.value.email,
  fullName: loggedInUser.value.fullName,
  avatar: null
})

const deleteAccountForm = useForm({
  password: undefined
})

function updateProfile(e) {
  e.preventDefault()
  form.patch('/settings/profile', {
    preserveScroll: true,
    preserveState: true,
    onError: (errors) => {
      console.error('Update failed:', errors)
    }
  })
}

function confirmDeleteAccount() {
  confirm.require({
    message:
      'Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.',
    header: 'Delete Account',
    icon: 'pi pi-exclamation-triangle',
    acceptClass: 'p-button-danger',
    accept: () => {
      deleteAccountForm.delete('/settings/profile')
    }
  })
}

function signOutEverywhere() {
  router.delete('/logout')
}
</script>

<script>
import DashboardLayout from '@/layouts/DashboardLayout.vue'

export default {
  layout: DashboardLayout
}
</script>

<template>
  <Head title="Profile Settings | Ascent Vue" />
  <ConfirmDialog :style="{ width: '32rem' }" />

  <div class="max-w-2xl space-y-12">
    <!-- Profile Header -->
    <header class="flex items-center space-x-4">
      <Avatar
        :image="loggedInUser.currentAvatarUrl"
        :label="loggedInUser.initials"
        size="large"
        shape="circle"
      />
      <div>
        <h2 class="text-lg font-medium text-gray-900">
          {{ loggedInUser.fullName }}
        </h2>
        <p class="text-sm text-gray-500">{{ loggedInUser.email }}</p>
      </div>
    </header>

    <!-- Profile Information -->
    <section class="space-y-6">
      <div>
        <h3 class="mb-4 text-sm font-medium text-gray-900">
          Profile Information
        </h3>
        <p class="mb-6 text-sm text-gray-500">
          Update your personal details and contact information.
        </p>
      </div>

      <form @submit="updateProfile" class="space-y-4">
        <!-- Avatar Upload -->
        <div>
          <label class="mb-2 block text-sm font-medium text-gray-700">
            Avatar
          </label>
          <ImageUpload
            :current-image-url="loggedInUser.avatarUrl"
            @image-select="(file) => (form.avatar = file)"
          />
          <Message
            v-if="form.errors.avatar"
            severity="error"
            :text="form.errors.avatar"
            class="mt-2"
          />
        </div>

        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <label for="fullName" class="mb-1 block text-sm text-gray-700">
              Full Name
            </label>
            <InputText id="fullName" v-model="form.fullName" class="w-full" />
          </div>

          <div>
            <label for="email" class="mb-1 block text-sm text-gray-700">
              Email Address
            </label>
            <InputText
              id="email"
              v-model="form.email"
              type="email"
              class="w-full"
            />
          </div>
        </div>
        <div class="flex items-center justify-end space-x-3">
          <span v-if="form.recentlySuccessful" class="text-sm text-green-600">
            Saved
          </span>
          <Button
            type="submit"
            :label="form.processing ? 'Saving changes...' : 'Save changes'"
            :loading="form.processing"
            size="small"
            outlined
          />
        </div>
      </form>
    </section>

    <!-- Account Actions -->
    <section class="space-y-6">
      <div>
        <h3 class="mb-4 text-sm font-medium text-gray-900">Account Actions</h3>
        <p class="mb-6 text-sm text-gray-500">
          Manage your account security and data.
        </p>
      </div>

      <div class="space-y-4">
        <!-- Sign out everywhere card -->
        <div
          class="rounded-lg border border-orange-200 bg-orange-50 p-4 shadow-sm sm:p-6"
        >
          <div
            class="flex flex-col space-y-4 sm:flex-row sm:items-start sm:justify-between sm:space-y-0"
          >
            <div class="flex items-start space-x-3">
              <div
                class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-orange-50"
              >
                <i class="pi pi-sign-out text-orange-600" />
              </div>
              <div class="min-w-0 flex-1">
                <h4 class="text-sm font-medium text-orange-900">
                  Sign out everywhere
                </h4>
                <p class="mt-1 text-sm text-orange-700">
                  Sign out from all devices and browser sessions for enhanced
                  security.
                </p>
              </div>
            </div>
            <div class="flex justify-end sm:ml-4 sm:shrink-0">
              <Button
                label="Sign out"
                @click="signOutEverywhere"
                size="small"
                class="w-full px-4 py-2 text-sm sm:w-auto"
                outlined
                severity="warning"
                icon="pi pi-sign-out"
              />
            </div>
          </div>
        </div>

        <!-- Delete account card -->
        <div
          class="rounded-lg border border-red-200 bg-red-50 p-4 shadow-sm sm:p-6"
        >
          <div
            class="flex flex-col space-y-4 sm:flex-row sm:items-start sm:justify-between sm:space-y-0"
          >
            <div class="flex items-start space-x-3">
              <div
                class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-red-100"
              >
                <i class="pi pi-trash text-red-600" />
              </div>
              <div class="min-w-0 flex-1">
                <h4 class="text-sm font-medium text-red-900">Delete account</h4>
                <p class="mt-1 text-sm text-red-700">
                  Permanently delete your account and all associated data. This
                  action cannot be undone.
                </p>
              </div>
            </div>
            <div class="flex justify-end sm:ml-4 sm:shrink-0">
              <Button
                label="Delete"
                @click="confirmDeleteAccount"
                severity="danger"
                size="small"
                class="w-full px-4 py-2 text-sm sm:w-auto"
                icon="pi pi-trash"
                outlined
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
