// templates/ascent-react/assets/js/pages/blog.jsx
import Input from '@/components/ui/input/Input.jsx'
import Newspaper from '@/components/ui/icons/Newspaper.jsx'
import ArrowRight from '@/components/ui/icons/ArrowRight.jsx'
import { Head, Link } from '@inertiajs/react'
import AppLayout from '@/layouts/AppLayout.jsx'

Blog.layout = AppLayout

export default function Blog({ appName, blogPosts }) {
  return (
    <>
      <Head title="Blog - Latest Updates & Insights | Ascent React" />

      {/* Hero Section */}
      <section className="relative overflow-hidden px-4 pb-16 pt-20">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-50/30 via-white to-accent-50/20"></div>
        <div className="absolute left-1/2 top-20 h-96 w-96 -translate-x-1/2 transform rounded-full bg-brand-100/20 blur-3xl"></div>

        <div className="relative mx-auto max-w-4xl text-center">
          <div className="mb-6">
            <span className="inline-flex items-center rounded-full bg-brand-100 px-4 py-2 text-sm font-semibold text-brand-700">
              📚 Latest Insights
            </span>
          </div>

          <h1 className="mb-6 text-5xl font-extrabold tracking-tight md:text-6xl">
            <span className="block leading-tight text-gray-900">{appName}</span>
            <span className="block bg-gradient-to-r from-brand-600 to-accent-600 bg-clip-text leading-tight text-transparent">
              Blog
            </span>
          </h1>

          <p className="mx-auto mb-10 max-w-2xl text-xl font-medium leading-relaxed text-gray-600">
            Stay up to date with the latest news, updates, and insights about
            building modern SaaS applications with The Boring Stack.
          </p>
        </div>
      </section>

      {/* Blog Posts */}
      <section className="relative bg-white px-4 pb-20">
        <div className="mx-auto max-w-4xl">
          {blogPosts && blogPosts.length > 0 ? (
            <div className="space-y-12">
              {blogPosts.map((post, index) => (
                <article
                  key={post.slug}
                  className="group relative rounded-2xl border border-gray-100 bg-white p-8 shadow-sm transition-all duration-300 hover:border-brand-200 hover:shadow-xl"
                >
                  <div className="flex flex-col space-y-6 sm:flex-row sm:items-start sm:space-x-8 sm:space-y-0">
                    {/* Date */}
                    <div className="flex-shrink-0">
                      <time className="inline-flex items-center rounded-full bg-brand-50 px-4 py-2 text-sm font-medium text-brand-700">
                        {post.publishedOn}
                      </time>
                    </div>

                    {/* Content */}
                    <div className="flex-1 space-y-4">
                      <h2 className="text-2xl font-bold text-gray-900 transition-colors group-hover:text-brand-600">
                        <a
                          href={`/blog/${post.slug}`}
                          className="hover:underline"
                        >
                          {post.title}
                        </a>
                      </h2>

                      <p className="text-lg leading-relaxed text-gray-600">
                        {post.description}
                      </p>

                      <div className="flex items-center justify-between">
                        <a
                          href={`/blog/${post.slug}`}
                          className="group/link inline-flex items-center font-semibold text-brand-600 transition-colors hover:text-brand-700"
                        >
                          Read full article
                          <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover/link:translate-x-1" />
                        </a>

                        {index === 0 && (
                          <span className="inline-flex items-center rounded-full bg-accent-100 px-3 py-1 text-xs font-semibold text-accent-800">
                            Latest
                          </span>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Hover effect gradient */}
                  <div className="absolute inset-0 -z-10 rounded-2xl bg-gradient-to-r from-brand-500/5 to-accent-500/5 opacity-0 transition-opacity group-hover:opacity-100"></div>
                </article>
              ))}
            </div>
          ) : (
            <div className="py-20 text-center" role="status" aria-live="polite">
              <div className="mx-auto mb-8 flex h-24 w-24 items-center justify-center rounded-full bg-gray-100">
                <Newspaper className="h-12 w-12 text-gray-400" />
              </div>
              <h3 className="mb-3 text-2xl font-bold text-gray-900">
                No blog posts yet
              </h3>
              <p className="mb-8 text-lg text-gray-600">
                Check back soon for updates and insights about building with
                Ascent React.
              </p>
              <Link
                href="/features"
                className="inline-flex items-center rounded-lg bg-brand-600 px-6 py-3 font-semibold text-white transition-all duration-200 hover:bg-brand-700"
              >
                Explore Features
              </Link>
            </div>
          )}

          {/* Newsletter Signup */}
          {blogPosts && blogPosts.length > 0 && (
            <div className="relative mt-20 overflow-hidden rounded-3xl bg-gradient-to-br from-gray-900 via-gray-800 to-brand-900 px-8 py-12 text-center text-white">
              {/* Background decoration */}
              <div className="absolute left-1/4 top-0 h-32 w-32 rounded-full bg-brand-500/10 blur-3xl"></div>
              <div className="absolute bottom-0 right-1/4 h-24 w-24 rounded-full bg-accent-500/10 blur-3xl"></div>

              <div className="relative mx-auto max-w-2xl">
                <h3 className="mb-4 text-3xl font-bold">
                  Never miss an update
                </h3>
                <p className="mb-8 text-xl text-gray-300">
                  Get the latest insights about SaaS development and product
                  launches delivered to your inbox.
                </p>
                <form className="mx-auto flex max-w-md flex-col justify-center gap-4 sm:flex-row">
                  <Input
                    type="email"
                    id="newsletter-email"
                    placeholder="Enter your email"
                    aria-label="Email address for newsletter subscription"
                    className="flex-1 rounded-lg border border-white/20 bg-white/10 px-4 py-3 text-white placeholder-gray-400 transition-all focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-400/50"
                    required
                  />
                  <button
                    type="submit"
                    className="rounded-lg bg-gradient-to-r from-brand-600 to-accent-600 px-8 py-3 font-semibold text-white transition-all duration-200 hover:shadow-lg"
                  >
                    Subscribe
                  </button>
                </form>
              </div>
            </div>
          )}
        </div>
      </section>
    </>
  )
}

// templates/ascent-vue/assets/js/pages/blog.vue
<script setup>
import Input from '@/components/ui/input/Input.vue'

import Newspaper from '@/components/ui/icons/Newspaper.vue'
import ArrowRight from '@/components/ui/icons/ArrowRight.vue'
import { Head, Link } from '@inertiajs/vue3'
import AppLayout from '@/layouts/AppLayout.vue'

defineOptions({
  layout: AppLayout
})

defineProps({
  appName: String,
  blogPosts: Array
})
</script>

<template>
  <Head title="Blog - Latest Updates & Insights | Ascent React" />

  <section class="relative overflow-hidden px-4 pt-20 pb-16">
    <div
      class="from-brand-50/30 to-accent-50/20 absolute inset-0 bg-linear-to-br via-white"
    ></div>
    <div
      class="bg-brand-100/20 absolute top-20 left-1/2 h-96 w-96 -translate-x-1/2 transform rounded-full blur-3xl"
    ></div>

    <div class="relative mx-auto max-w-4xl text-center">
      <div class="mb-6">
        <span
          class="bg-brand-100 text-brand-700 inline-flex items-center rounded-full px-4 py-2 text-sm font-semibold"
        >
          📚 Latest Insights
        </span>
      </div>

      <h1 class="mb-6 text-5xl font-extrabold tracking-tight md:text-6xl">
        <span class="block leading-tight text-gray-900">{{ appName }}</span>
        <span
          class="bg-linear-to-rrom-brand-600 to-accent-600 block bg-clip-text leading-tight text-transparent"
        >
          Blog
        </span>
      </h1>

      <p
        class="mx-auto mb-10 max-w-2xl text-xl leading-relaxed font-medium text-gray-600"
      >
        Stay up to date with the latest news, updates, and insights about
        building modern SaaS applications with The Boring Stack.
      </p>
    </div>
  </section>

  <section class="relative bg-white px-4 pb-20">
    <div class="mx-auto max-w-4xl">
      <div v-if="blogPosts && blogPosts.length > 0" class="space-y-12">
        <article
          v-for="(post, index) in blogPosts"
          :key="post.slug"
          class="group hover:border-brand-300 relative rounded-2xl border border-gray-300 bg-white p-8 shadow-sm transition-all duration-300 hover:shadow-xl"
        >
          <div
            class="flex flex-col space-y-6 sm:flex-row sm:items-start sm:space-y-0 sm:space-x-8"
          >
            <div class="shrink-0">
              <time
                class="bg-brand-50 text-brand-700 inline-flex items-center rounded-full px-4 py-2 text-sm font-medium"
              >
                {{ post.publishedOn }}
              </time>
            </div>

            <div class="flex-1 space-y-4">
              <h2
                class="group-hover:text-brand-600 text-2xl font-bold text-gray-900 transition-colors"
              >
                <a :href="`/blog/${post.slug}`" class="hover:underline">
                  {{ post.title }}
                </a>
              </h2>

              <p class="text-lg leading-relaxed text-gray-600">
                {{ post.description }}
              </p>

              <div class="flex items-center justify-between">
                <a
                  :href="`/blog/${post.slug}`"
                  class="group/link text-brand-600 hover:text-brand-700 inline-flex items-center font-semibold transition-colors"
                >
                  Read full article
                  <ArrowRight
                    class="ml-2 h-4 w-4 transition-transform group-hover/link:translate-x-1"
                  />
                </a>

                <span
                  v-if="index === 0"
                  class="bg-accent-100 text-accent-800 inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold"
                >
                  Latest
                </span>
              </div>
            </div>
          </div>

          <div
            class="from-brand-500/5 to-accent-500/5 absolute inset-0 -z-10 rounded-2xl bg-linear-to-r opacity-0 transition-opacity group-hover:opacity-100"
          ></div>
        </article>
      </div>

      <div v-else class="py-20 text-center" role="status" aria-live="polite">
        <div
          class="mx-auto mb-8 flex h-24 w-24 items-center justify-center rounded-full bg-gray-100"
        >
          <Newspaper class="h-12 w-12 text-gray-400" />
        </div>
        <h3 class="mb-3 text-2xl font-bold text-gray-900">No blog posts yet</h3>
        <p class="mb-8 text-lg text-gray-600">
          Check back soon for updates and insights about building with Ascent
          React.
        </p>
        <Link
          href="/features"
          class="bg-brand-600 hover:bg-brand-700 inline-flex items-center rounded-lg px-6 py-3 font-semibold text-white transition-all duration-200"
        >
          Explore Features
        </Link>
      </div>

      <div
        v-if="blogPosts && blogPosts.length > 0"
        class="to-brand-900 relative mt-20 overflow-hidden rounded-3xl bg-linear-to-br from-gray-900 via-gray-800 px-8 py-12 text-center text-white"
      >
        <div
          class="bg-brand-500/10 absolute top-0 left-1/4 h-32 w-32 rounded-full blur-3xl"
        ></div>
        <div
          class="bg-accent-500/10 absolute right-1/4 bottom-0 h-24 w-24 rounded-full blur-3xl"
        ></div>

        <div class="relative mx-auto max-w-2xl">
          <h3 class="mb-4 text-3xl font-bold">Never miss an update</h3>
          <p class="mb-8 text-xl text-gray-300">
            Get the latest insights about SaaS development and product launches
            delivered to your inbox.
          </p>
          <form
            class="mx-auto flex max-w-md flex-col justify-center gap-4 sm:flex-row"
          >
            <Input
              type="email"
              id="newsletter-email"
              placeholder="Enter your email"
              aria-label="Email address for newsletter subscription"
              class="focus:border-brand-400 focus:ring-brand-400/50 flex-1 rounded-lg border border-white/20 bg-white/10 px-4 py-3 text-white placeholder-gray-400 transition-all focus:ring-2 focus:outline-none"
              required
            />
            <button
              type="submit"
              class="from-brand-600 to-accent-600 rounded-lg bg-linear-to-r px-8 py-3 font-semibold text-white transition-all duration-200 hover:shadow-lg"
            >
              Subscribe
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
