// templates/mellow-vue/assets/js/pages/error.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3'

const props = defineProps({
  status: {
    type: Number,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  }
})

const homeHref = props.status === 404 ? '/' : '/dashboard'
</script>

<template>
  <Head :title="`${status} ${title} | Mellow`" />

  <main class="mellow-auth">
    <section class="mx-auto w-full max-w-3xl">
      <p class="text-brand mb-4 text-sm font-semibold">Status {{ status }}</p>
      <h1 class="max-w-2xl text-4xl font-semibold text-black sm:text-5xl">
        {{ title }}
      </h1>
      <p class="mt-5 max-w-xl text-lg leading-8 text-gray-600">
        {{ message }}
      </p>

      <div class="mt-8 flex flex-wrap items-center gap-3">
        <Link
          :href="homeHref"
          class="min-h-11 bg-brand hover:bg-brand-600 focus:ring-brand-100 inline-flex items-center justify-center rounded-md px-5 text-sm font-semibold text-white shadow-sm transition focus:outline-none focus:ring-2"
        >
          Go home
        </Link>
        <button
          type="button"
          class="min-h-11 inline-flex items-center justify-center rounded-md border border-gray-200 bg-white px-5 text-sm font-semibold text-black shadow-sm transition hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-200"
          @click="history.back()"
        >
          Go back
        </button>
      </div>
    </section>
  </main>
</template>

// templates/mellow-svelte/assets/js/pages/error.svelte
<script>
  import { Link } from '@inertiajs/svelte'

  export let status
  export let title
  export let message

  $: homeHref = status === 404 ? '/' : '/dashboard'
</script>

<svelte:head>
  <title>{status} {title} | Mellow</title>
</svelte:head>

<main class="mellow-auth">
  <section class="mx-auto w-full max-w-3xl">
    <p class="text-brand mb-4 text-sm font-semibold">Status {status}</p>
    <h1 class="max-w-2xl text-4xl font-semibold text-black sm:text-5xl">
      {title}
    </h1>
    <p class="mt-5 max-w-xl text-lg leading-8 text-gray-600">
      {message}
    </p>

    <div class="mt-8 flex flex-wrap items-center gap-3">
      <Link
        href={homeHref}
        class="bg-brand hover:bg-brand-600 focus:ring-brand-100 inline-flex min-h-11 items-center justify-center rounded-md px-5 text-sm font-semibold text-white shadow-sm transition focus:ring-2 focus:outline-none"
      >
        Go home
      </Link>
      <button
        type="button"
        class="inline-flex min-h-11 items-center justify-center rounded-md border border-gray-200 bg-white px-5 text-sm font-semibold text-black shadow-sm transition hover:bg-gray-50 focus:ring-2 focus:ring-gray-200 focus:outline-none"
        on:click={() => history.back()}
      >
        Go back
      </button>
    </div>
  </section>
</main>
