// templates/mellow-vue/assets/js/pages/index.vue
<script setup>
import { Head } from '@inertiajs/vue3'
import AppLayout from '@/layouts/AppLayout.vue'

defineOptions({
  layout: AppLayout
})
</script>

<template>
  <Head title="Simplify Authentication, Focus on Shipping | Mellow"></Head>
  <section class="mx-4 mt-20">
    <h1 class="text-brand mb-4 text-center text-4xl font-bold md:text-5xl">
      Simplify Authentication, Focus on Shipping 🚀
    </h1>
    <p class="mx-auto max-w-3xl text-center text-xl text-gray-600">
      Mellow handles user management, so you can build what matters.
    </p>
  </section>
  <section class="px-4 py-12 md:mx-auto md:w-10/12 md:px-8 md:py-16">
    <div class="grid grid-cols-1 gap-8 md:grid-cols-2">
      <a
        href="https://marketplace.visualstudio.com/items?itemName=Sails.sails-vscode"
        target="_blank"
        rel="noopener noreferrer"
        class="from-brand-50/10 group block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
      >
        <h3 class="text-brand mb-2 text-xl font-semibold">
          Official VS Code extension
        </h3>
        <p class="mb-4 text-gray-600">
          Install the official Sails VS Code extension to supercharge your
          development experience.
        </p>
        <button
          class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
        >
          Install Extension
        </button>
      </a>

      <a
        href="https://sailsjs.com/documentation"
        target="_blank"
        rel="noopener noreferrer"
        class="from-brand-50/10 group block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
      >
        <h3 class="text-brand mb-2 text-xl font-semibold">
          The Boring JavaScript Stack Docs
        </h3>
        <p class="mb-4 text-gray-600">
          Official documentation for The Boring JavaScript Stack.
        </p>
        <button
          class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
        >
          Read Docs
        </button>
      </a>
      <a
        href="https://sailscasts.com/chat"
        target="_blank"
        rel="noopener noreferrer"
        class="from-brand-50/10 group block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
      >
        <h3 class="text-brand mb-2 text-xl font-semibold">
          Sailscasts Discord
        </h3>
        <p class="mb-4 text-gray-600">
          Join the community to discuss Sails.js and get help. Connect with
          fellow developers and stay updated.
        </p>
        <button
          class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
        >
          Join Community
        </button>
      </a>

      <a
        href="https://github.com/sailscastshq/boring-stack"
        target="_blank"
        rel="noopener noreferrer"
        class="from-brand-50/10 group block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
      >
        <h3 class="text-brand mb-2 text-xl font-semibold">
          Star on GitHub ⭐️
        </h3>
        <p class="mb-4 text-gray-600">
          Give The Boring JavaScript Stack a star on GitHub.
        </p>
        <button
          class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
        >
          Star Project
        </button>
      </a>
      <a
        href="https://sailscasts.com"
        target="_blank"
        rel="noopener noreferrer"
        class="from-brand-50/10 group block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
      >
        <h3 class="text-brand mb-2 text-xl font-semibold">Sailscasts</h3>
        <p class="mb-4 text-gray-600">
          Learn Sails.js and The Boring JavaScript Stack through video tutorials
          and courses.
        </p>
        <button
          class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
        >
          Start Learning
        </button>
      </a>
    </div>
  </section>
  <section
    class="space-y-8 px-4 py-8 md:grid md:grid-cols-2 md:gap-12 md:space-y-0 md:p-12"
  >
    <article>
      <h3 class="text-brand text-xl md:mb-2 md:text-2xl">Productivity</h3>
      <p class="text-gray font-light md:text-lg">
        Let Mellow be the starting point of your next SPA. With authentication
        and profile management taken care of, you can focus on your core
        business logic
      </p>
    </article>
    <article>
      <h3 class="text-brand text-xl md:mb-2 md:text-2xl">
        Seamless authentication
      </h3>
      <p class="text-gray font-light md:text-lg">
        Experience effortless user authentication and simplified profile
        management with Mellow, creating a seamless user journey for developers
        and users.
      </p>
    </article>
    <article>
      <h3 class="text-brand text-xl md:mb-2 md:text-2xl">Profile management</h3>
      <p class="text-gray font-light md:text-lg">
        Let users manage their profiles with ease using Mellow. It offers a
        simple and secure way to update their name, email address, and password.
      </p>
    </article>
  </section>
  <section class="bg-[#F9FAFB] px-4 py-8 md:flex md:space-x-64 md:p-12">
    <h2 class="flex-grow-0 text-xl text-black md:w-2/12 md:text-3xl">
      Frequently asked questions
    </h2>
    <section class="flex-1">
      <details class="relative border-b border-[#D7D7D7] py-4">
        <summary class="text-gray md:text-lg">What is Mellow?</summary>
        <p class="text-sm text-black md:text-lg">
          Mellow is the default starter template for The Boring JavaScript
          Stack. It provides authentication and profile management out of the
          box.
        </p>
      </details>
      <details class="relative border-b border-[#D7D7D7] py-4">
        <summary class="text-gray md:text-lg">
          How do I get started with Mellow?
        </summary>
        <p class="text-sm text-black md:text-lg">
          Chances are you already have scaffolded a new project using Mellow if
          you are seeing this. Just open up the project in your editor and start
          coding away.
        </p>
      </details>
      <details class="relative border-b border-[#D7D7D7] py-4">
        <summary class="text-gray md:text-lg">Can I customize Mellow?</summary>
        <p class="text-sm text-black md:text-lg">
          For sure! All the code in Mellow is open source so you can copy and
          paste and customize to your heart's content.
        </p>
      </details>
    </section>
  </section>
</template>
<style>
details > summary {
  list-style: none;
}
summary::-webkit-details-marker {
  display: none;
}

summary::after {
  position: absolute;
  right: 0px;
  content: ' +';
}
@keyframes details-show {
  from {
    opacity: 0;
    transform: var(--details-translate, translateY(-0.5em));
  }
}

details[open] > *:not(summary) {
  animation: details-show 150ms ease-in-out;
}
details[open] summary:after {
  content: ' −';
}
</style>

// templates/mellow-svelte/assets/js/pages/index.svelte
<script context="module">
  import AppLayout from '@/layouts/AppLayout.svelte'
  export const layout = AppLayout
</script>

<svelte:head>
  <title>Simplify Authentication, Focus on Shipping | Mellow</title>
</svelte:head>
<section class="mx-4 mt-20">
  <h1 class="text-brand mb-4 text-center text-4xl font-bold md:text-5xl">
    Simplify Authentication, Focus on Shipping 🚀
  </h1>
  <p class="mx-auto max-w-3xl text-center text-xl text-gray-600">
    Mellow handles user management, so you can build what matters.
  </p>
</section>
<section class="px-4 py-12 md:mx-auto md:w-10/12 md:px-8 md:py-16">
  <div class="grid grid-cols-1 gap-8 md:grid-cols-2">
    <a
      href="https://marketplace.visualstudio.com/items?itemName=Sails.sails-vscode"
      target="_blank"
      rel="noopener noreferrer"
      class="group from-brand-50/10 block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
    >
      <h3 class="text-brand mb-2 text-xl font-semibold">
        Official VS Code extension
      </h3>
      <p class="mb-4 text-gray-600">
        Install the official Sails VS Code extension to supercharge your
        development experience.
      </p>
      <button
        class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
      >
        Install Extension
      </button>
    </a>

    <a
      href="https://sailsjs.com/documentation"
      target="_blank"
      rel="noopener noreferrer"
      class="group from-brand-50/10 block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
    >
      <h3 class="text-brand mb-2 text-xl font-semibold">
        The Boring JavaScript Stack Docs
      </h3>
      <p class="mb-4 text-gray-600">
        Official documentation for The Boring JavaScript Stack.
      </p>
      <button
        class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
      >
        Read Docs
      </button>
    </a>
    <a
      href="https://sailscasts.com/chat"
      target="_blank"
      rel="noopener noreferrer"
      class="group from-brand-50/10 block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
    >
      <h3 class="text-brand mb-2 text-xl font-semibold">Sailscasts Discord</h3>
      <p class="mb-4 text-gray-600">
        Join the community to discuss Sails.js and get help. Connect with fellow
        developers and stay updated.
      </p>
      <button
        class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
      >
        Join Community
      </button>
    </a>

    <a
      href="https://github.com/sailscastshq/boring-stack"
      target="_blank"
      rel="noopener noreferrer"
      class="group from-brand-50/10 block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
    >
      <h3 class="text-brand mb-2 text-xl font-semibold">Star on GitHub ⭐️</h3>
      <p class="mb-4 text-gray-600">
        Give The Boring JavaScript Stack a star on GitHub.
      </p>
      <button
        class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
      >
        Star Project
      </button>
    </a>
    <a
      href="https://sailscasts.com"
      target="_blank"
      rel="noopener noreferrer"
      class="group from-brand-50/10 block rounded-lg bg-gradient-to-b to-white p-6 shadow-md transition-all duration-300 hover:shadow-lg"
    >
      <h3 class="text-brand mb-2 text-xl font-semibold">Sailscasts</h3>
      <p class="mb-4 text-gray-600">
        Learn Sails.js and The Boring JavaScript Stack through video tutorials
        and courses.
      </p>
      <button
        class="border-brand text-brand group-hover:bg-brand mt-2 rounded-lg border px-4 py-2 transition-colors duration-300 group-hover:text-white"
      >
        Start Learning
      </button>
    </a>
  </div>
</section>
<section
  class="space-y-8 px-4 py-8 md:grid md:grid-cols-2 md:gap-12 md:space-y-0 md:p-12"
>
  <article>
    <h3 class="text-brand text-xl md:mb-2 md:text-2xl">Productivity</h3>
    <p class="text-gray font-light md:text-lg">
      Let Mellow be the starting point of your next SPA. With authentication and
      profile management taken care of, you can focus on your core business
      logic
    </p>
  </article>
  <article>
    <h3 class="text-brand text-xl md:mb-2 md:text-2xl">
      Seamless authentication
    </h3>
    <p class="text-gray font-light md:text-lg">
      Experience effortless user authentication and simplified profile
      management with Mellow, creating a seamless user journey for developers
      and users.
    </p>
  </article>
  <article>
    <h3 class="text-brand text-xl md:mb-2 md:text-2xl">Profile management</h3>
    <p class="text-gray font-light md:text-lg">
      Let users manage their profiles with ease using Mellow. It offers a simple
      and secure way to update their name, email address, and password.
    </p>
  </article>
</section>
<section class="bg-[#F9FAFB] px-4 py-8 md:flex md:space-x-64 md:p-12">
  <h2 class="flex-grow-0 text-xl text-black md:w-2/12 md:text-3xl">
    Frequently asked questions
  </h2>
  <section class="flex-1">
    <details class="relative border-b border-[#D7D7D7] py-4">
      <summary class="text-gray md:text-lg">What is Mellow?</summary>
      <p class="text-sm text-black md:text-lg">
        Mellow is the default starter template for The Boring JavaScript Stack.
        It provides authentication and profile management out of the box.
      </p>
    </details>
    <details class="relative border-b border-[#D7D7D7] py-4">
      <summary class="text-gray md:text-lg">
        How do I get started with Mellow?
      </summary>
      <p class="text-sm text-black md:text-lg">
        Chances are you already have scaffolded a new project using Mellow if
        you are seeing this. Just open up the project in your editor and start
        coding away.
      </p>
    </details>
    <details class="relative border-b border-[#D7D7D7] py-4">
      <summary class="text-gray md:text-lg">Can I customize Mellow?</summary>
      <p class="text-sm text-black md:text-lg">
        For sure! All the code in Mellow is open source so you can copy and
        paste and customize to your heart's content.
      </p>
    </details>
  </section>
</section>

<style>
  details > summary {
    list-style: none;
  }
  summary::-webkit-details-marker {
    display: none;
  }

  summary::after {
    position: absolute;
    right: 0px;
    content: ' +';
  }
  @keyframes details-show {
    from {
      opacity: 0;
      transform: var(--details-translate, translateY(-0.5em));
    }
  }

  details[open] > *:not(summary) {
    animation: details-show 150ms ease-in-out;
  }
  details[open] summary:after {
    content: ' −';
  }
</style>
