// templates/ascent-vue/assets/js/components/EmailTwoFactorSetupModal.jsx
import { useForm } from '@inertiajs/react'
import { Dialog } from 'primereact/dialog'
import { Button } from 'primereact/button'
import { InputOtp } from 'primereact/inputotp'
import { Message } from 'primereact/message'

export default function EmailTwoFactorSetupModal({
  visible,
  onHide,
  userEmail
}) {
  const { data, setData, post, processing, errors, reset } = useForm({
    code: ''
  })

  function handleVerifyCode(e) {
    e.preventDefault()
    post('/security/verify-email-2fa-setup', {
      onSuccess: () => {
        reset()
        // Allow reset to take effect before closing modal
        setTimeout(() => {
          onHide()
        }, 0)
      },
      onError: (errors) => {
        console.error('Email 2FA verification failed:', errors)
      }
    })
  }

  function handleClose() {
    reset()
    onHide()
  }

  // Don't render modal if no user email
  if (!userEmail) {
    return null
  }

  return (
    <Dialog
      visible={visible}
      onHide={handleClose}
      header={null}
      modal
      closable={!processing}
      className="mx-4 w-full max-w-lg sm:mx-0"
      contentStyle={{ paddingRight: '2rem', paddingLeft: '2rem' }}
    >
      <div className="space-y-8">
        {/* Header */}
        <div className="text-center">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-blue-50">
            <i className="pi pi-envelope text-2xl text-blue-600"></i>
          </div>
          <h2 className="mb-2 text-xl font-semibold text-gray-900">
            Verify Your Email
          </h2>
          <p className="text-sm text-gray-600">
            We've sent a 6-digit verification code to{' '}
            <strong>{userEmail}</strong>. Enter it below to enable email
            two-factor authentication.
          </p>
        </div>

        {/* Error Message */}
        {errors.code && (
          <Message
            severity="error"
            text={
              typeof errors.code === 'string'
                ? errors.code
                : 'Invalid verification code'
            }
          />
        )}

        {/* Verification Form */}
        <form onSubmit={handleVerifyCode} className="space-y-6">
          <div>
            <label className="mb-3 block text-sm font-medium text-gray-700">
              Enter verification code
            </label>
            <div className="flex justify-start">
              <InputOtp
                value={data.code}
                onChange={(e) => setData('code', e.value)}
                length={6}
                integerOnly
                mask
              />
            </div>
          </div>

          {/* Help Text */}
          <div className="rounded-lg border border-gray-200 bg-gray-50 p-4">
            <div className="flex">
              <div className="flex-shrink-0">
                <i className="pi pi-info-circle text-gray-400"></i>
              </div>
              <div className="ml-3">
                <p className="text-sm text-gray-600">
                  The verification code expires in 10 minutes. If you don't see
                  the email, check your spam folder.
                </p>
              </div>
            </div>
          </div>

          <div className="flex flex-col justify-end space-y-3 sm:flex-row sm:space-x-3 sm:space-y-0">
            <Button
              type="button"
              label="Cancel"
              severity="secondary"
              outlined
              onClick={handleClose}
              size="small"
              disabled={processing}
              className="w-full sm:w-auto"
            />
            <Button
              type="submit"
              label="Verify & Enable Email 2FA"
              size="small"
              loading={processing}
              disabled={!data.code || data.code.length !== 6}
              className="w-full sm:w-auto"
            />
          </div>
        </form>
      </div>
    </Dialog>
  )
}

// templates/ascent-vue/assets/js/components/EmailTwoFactorSetupModal.vue
<script setup>
import { useForm } from '@inertiajs/vue3'
import Dialog from '@/volt/Dialog.vue'
import Button from '@/volt/Button.vue'
import InputOtp from '@/volt/InputOtp.vue'
import Message from '@/volt/Message.vue'

const props = defineProps({
  visible: {
    type: Boolean,
    required: true
  },
  userEmail: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['hide'])

const form = useForm({
  code: ''
})

function handleVerifyCode() {
  form.post('/security/verify-email-2fa-setup', {
    onSuccess: () => {
      form.reset()
      // Allow reset to take effect before closing modal
      setTimeout(() => {
        emit('hide')
      }, 0)
    },
    onError: (errors) => {
      console.error('Email 2FA verification failed:', errors)
    }
  })
}

function handleClose() {
  form.reset()
  emit('hide')
}
</script>

<template>
  <!-- Don't render modal if no user email -->
  <Dialog
    v-if="userEmail"
    :visible="visible"
    :modal="true"
    :closable="!form.processing"
    class="mx-4 w-full max-w-lg sm:mx-0"
    :content-style="{ paddingRight: '2rem', paddingLeft: '2rem' }"
    @update:visible="handleClose"
  >
    <div class="space-y-8">
      <!-- Header -->
      <div class="text-center">
        <div
          class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-blue-50"
        >
          <i class="pi pi-envelope text-2xl text-blue-600" />
        </div>
        <h2 class="mb-2 text-xl font-semibold text-gray-900">
          Verify Your Email
        </h2>
        <p class="text-sm text-gray-600">
          We've sent a 6-digit verification code to{' '}
          <strong>{{ userEmail }}</strong
          >. Enter it below to enable email two-factor authentication.
        </p>
      </div>

      <!-- Error Message -->
      <Message v-if="form.errors.code" severity="error">
        {{
          typeof form.errors.code === 'string'
            ? form.errors.code
            : 'Invalid verification code'
        }}
      </Message>

      <!-- Verification Form -->
      <form @submit.prevent="handleVerifyCode" class="space-y-6">
        <div>
          <label class="mb-3 block text-sm font-medium text-gray-700">
            Enter verification code
          </label>
          <div class="flex justify-start">
            <InputOtp v-model="form.code" :length="6" integer-only mask />
          </div>
        </div>

        <!-- Help Text -->
        <div class="rounded-lg border border-gray-200 bg-gray-50 p-4">
          <div class="flex">
            <div class="shrink-0">
              <i class="pi pi-info-circle text-gray-400" />
            </div>
            <div class="ml-3">
              <p class="text-sm text-gray-600">
                The verification code expires in 10 minutes. If you don't see
                the email, check your spam folder.
              </p>
            </div>
          </div>
        </div>

        <div
          class="flex flex-col justify-end space-y-3 sm:flex-row sm:space-x-3 sm:space-y-0"
        >
          <Button
            type="button"
            label="Cancel"
            severity="secondary"
            outlined
            size="small"
            :disabled="form.processing"
            class="w-full sm:w-auto"
            @click="handleClose"
          />
          <Button
            type="submit"
            label="Verify & Enable Email 2FA"
            size="small"
            :loading="form.processing"
            :disabled="!form.code || form.code.length !== 6"
            class="w-full sm:w-auto"
          />
        </div>
      </form>
    </div>
  </Dialog>
</template>
