// templates/mellow-react/assets/js/components/InputEmail.jsx
import Envelope from '@/components/ui/icons/Envelope.jsx'
import InputBase from '@/components/InputBase'

export default function InputEmail(props) {
  return (
    <InputBase
      label="Email"
      id="email"
      type="email"
      placeholder="Your email"
      icon={<Envelope className="text-gray h-5 w-5" />}
      {...props}
    />
  )
}

// templates/mellow-vue/assets/js/components/InputEmail.vue
<script setup>
import Envelope from '@/components/ui/icons/Envelope.vue'

import InputBase from '@/components/InputBase.vue'

defineProps({
  label: {
    type: String,
    default: 'Email'
  },
  id: {
    type: String,
    default: 'email'
  },
  placeholder: {
    type: String,
    default: 'Your email'
  },
  error: {
    type: String,
    default: ''
  }
})
</script>

<template>
  <InputBase
    :label="label"
    :id="id"
    type="email"
    :placeholder="placeholder"
    :error="error"
  >
    <template #icon>
      <Envelope class="text-gray h-5 w-5" />
    </template>
    <slot></slot>
  </InputBase>
</template>
